// ═══════════════════════════════════════════════
// Analytics — Unified AARRR Event Tracking
//
// Single entry point for all growth analytics.
// Fans out to: GA4 (if loaded), internal event_queue, console (dev).
//
// Usage:
//   import { track } from "@/lib/analytics";
//   track("aarrr.activation.first_plan_generated", { planId, industry });
// ═══════════════════════════════════════════════

import { publishEvent, type EventType } from "@/services/eventQueue";
import { safeSessionStorage } from "./safeStorage";

// ─── North Star Metric ───────────────────────────
// Single metric that drives all product decisions.
// Measured as: count of first_plan_generated events in the trailing 7 days.
// Review weekly at /admin/aarrr.
export const NORTH_STAR_METRIC = {
  id: "weekly_activated_plans",
  event: "aarrr.activation.first_plan_generated" as const,
  description: "Plans generated by users in the trailing 7 days",
  target: 25,
  unit: { he: "תוכניות/שבוע", en: "plans/week" },
} as const;

// ─── Types ──────────────────────────────────────

export type AARRRStage = "acquisition" | "activation" | "retention" | "revenue" | "referral";

/** All AARRR event names */
export type AARRREventName =
  // Acquisition
  | "aarrr.acquisition.landing_view"
  | "aarrr.acquisition.signup_started"
  | "aarrr.acquisition.signup_completed"
  | "aarrr.acquisition.onboarding_started"
  | "aarrr.acquisition.utm_captured"
  // Activation
  | "aarrr.activation.onboarding_completed"
  | "aarrr.activation.first_plan_generated"
  | "aarrr.activation.first_template_copied"
  | "aarrr.activation.first_share_created"
  | "aarrr.activation.archetype_revealed"
  | "aarrr.activation.aha_moment"
  | "aarrr.activation.onboarding_abandoned"
  | "aarrr.activation.first_lead_logged"
  // Retention
  | "aarrr.retention.weekly_active"
  | "aarrr.retention.monthly_active"
  | "aarrr.retention.streak_broken"
  | "aarrr.retention.reactivated"
  | "aarrr.retention.pulse_opened"
  | "aarrr.retention.blind_spot_nudge_clicked"
  | "aarrr.retention.cadence_hint_shown"
  | "aarrr.retention.loop_continued"
  | "aarrr.retention.loop_new_move"
  // Revenue
  | "aarrr.revenue.paywall_viewed"
  | "aarrr.revenue.checkout_started"
  | "aarrr.revenue.conversion_completed"
  | "aarrr.revenue.upgrade"
  | "aarrr.revenue.downgrade"
  | "aarrr.revenue.churned"
  // Referral
  | "aarrr.referral.share_created"
  | "aarrr.referral.share_viewed"
  | "aarrr.referral.signup_from_share"
  | "aarrr.referral.reward_earned"
  | "aarrr.referral.referral_clicked";

export type AnalyticsEventName = AARRREventName | EventType;

export interface TrackOptions {
  userId?: string;
  /** Set to true to skip queueing to event_queue (use for high-frequency UI events) */
  uiOnly?: boolean;
}

// ─── GA4 helpers ────────────────────────────────

declare global {
  interface Window {
    gtag?: (...args: unknown[]) => void;
    dataLayer?: unknown[];
  }
}

function sendToGA4(eventName: string, props: Record<string, unknown>) {
  try {
    if (typeof window !== "undefined" && typeof window.gtag === "function") {
      // Convert AARRR dot-notation to GA4 snake_case (max 40 chars)
      const ga4Name = eventName.replace(/\./g, "_").slice(0, 40);
      window.gtag("event", ga4Name, props);
    }
  } catch {
    // GA4 unavailable — continue silently
  }
}

// ─── Stage extraction ────────────────────────────

export function getStageFromEvent(name: AARRREventName): AARRRStage {
  if (name.startsWith("aarrr.acquisition")) return "acquisition";
  if (name.startsWith("aarrr.activation")) return "activation";
  if (name.startsWith("aarrr.retention")) return "retention";
  if (name.startsWith("aarrr.revenue")) return "revenue";
  return "referral";
}

// ─── Main track function ─────────────────────────

/**
 * Track an AARRR or system event.
 * - Sends to GA4 (if loaded).
 * - Publishes to internal event_queue (for dashboard + training_pairs).
 * - Logs to console in development.
 *
 * Returns a promise that resolves when the queue publish completes.
 * Fire-and-forget is safe: errors are swallowed.
 */
export async function track(
  eventName: AARRREventName,
  props: Record<string, unknown> = {},
  options: TrackOptions = {}
): Promise<void> {
  const enriched = {
    ...props,
    _ts: Date.now(),
    _url: typeof window !== "undefined" ? window.location.pathname : undefined,
    _referrer: typeof document !== "undefined" ? document.referrer || undefined : undefined,
  };

  // 1. GA4
  sendToGA4(eventName, enriched);

  // 2. Dev console
  if (import.meta.env.DEV) {
    const stage = getStageFromEvent(eventName as AARRREventName);
    const STAGE_COLORS: Record<AARRRStage, string> = {
      acquisition: "#3b82f6",
      activation: "#10b981",
      retention: "#f59e0b",
      revenue: "#ef4444",
      referral: "#8b5cf6",
    };
    console.log(
      `%c[AARRR:${stage.toUpperCase()}] %c${eventName}`,
      `color: ${STAGE_COLORS[stage]}; font-weight: bold`,
      "color: inherit",
      enriched
    );
  }

  // 3. Internal event_queue
  if (!options.uiOnly && options.userId) {
    try {
      await publishEvent(
        "notification.send", // piggyback on existing event type
        { aarrrEvent: eventName, ...enriched },
        options.userId,
        { priority: 8 } // low priority — don't starve plan generation
      );
    } catch {
      // Non-critical — continue silently
    }
  }
}

// ─── Convenience shortcuts ───────────────────────

export const Analytics = {
  // Acquisition
  landingView: (props?: Record<string, unknown>, userId?: string) =>
    track("aarrr.acquisition.landing_view", props, { userId }),
  signupCompleted: (userId: string, props?: Record<string, unknown>) =>
    track("aarrr.acquisition.signup_completed", props, { userId }),
  utmCaptured: (utm: Record<string, string>, userId?: string) =>
    track("aarrr.acquisition.utm_captured", utm, { userId }),

  // Activation
  // NOTE: historically there was only `onboardingStarted` wired to the
  // `onboarding_completed` event (inherited name). Both helpers remain so
  // existing call sites keep working; prefer `onboardingCompleted` for new
  // call sites so the intent is readable.
  onboardingStarted: (userId?: string) => {
    safeSessionStorage.setJSON("funnelforge_ttfv_start", Date.now());
    return track("aarrr.activation.onboarding_completed", {}, { userId });
  },
  onboardingCompleted: (userId: string, source?: "express" | "full") =>
    track("aarrr.activation.onboarding_completed", { source }, { userId }),
  firstPlanGenerated: (planId: string, userId: string, industry?: string) => {
    const startTs = safeSessionStorage.getJSON<number | null>("funnelforge_ttfv_start", null);
    const ttfv_ms = startTs != null ? Date.now() - startTs : undefined;
    return track("aarrr.activation.first_plan_generated", { planId, industry, ttfv_ms }, { userId });
  },
  firstTemplateCopied: (userId: string, channel?: string) =>
    track("aarrr.activation.first_template_copied", { channel }, { userId }),
  archetypeRevealed: (userId: string, archetype: string) =>
    track("aarrr.activation.archetype_revealed", { archetype }, { userId }),
  ahaMoment: (userId: string, trigger: string) =>
    track("aarrr.activation.aha_moment", { trigger }, { userId }),
  onboardingAbandoned: (step: number, userId?: string) =>
    track("aarrr.activation.onboarding_abandoned", { step }, { userId }),
  firstLeadLogged: (userId: string, leadId: string, source?: string) =>
    track("aarrr.activation.first_lead_logged", { leadId, source }, { userId }),

  // Retention
  weeklyActive: (userId: string) =>
    track("aarrr.retention.weekly_active", {}, { userId }),
  streakBroken: (streak: number, userId: string) =>
    track("aarrr.retention.streak_broken", { streak }, { userId }),
  reactivated: (daysSilent: number, userId: string) =>
    track("aarrr.retention.reactivated", { daysSilent }, { userId }),
  pulseOpened: (userId: string) =>
    track("aarrr.retention.pulse_opened", {}, { userId }),

  // Weekly-loop cadence — fires once per state entry when the cadence text
  // is rendered in WeeklyActionCard. Paired with later commit/report events
  // to measure whether exposure to the cadence language correlates with
  // staying in the loop.
  cadenceHintShown: (userId: string, loopState: string) =>
    track("aarrr.retention.cadence_hint_shown", { loopState }, { userId }),

  // Fired when a user in between_weeks chooses to run another cycle on the
  // same action. Complementary to loopNewMove — ratio tells us whether the
  // loop is a real cadence or just a one-shot wizard dressed as a loop.
  loopContinued: (userId: string, module: string) =>
    track("aarrr.retention.loop_continued", { module }, { userId }),

  loopNewMove: (userId: string, module: string) =>
    track("aarrr.retention.loop_new_move", { module }, { userId }),

  // Revenue
  paywallViewed: (feature: string, tier: string, userId: string) =>
    track("aarrr.revenue.paywall_viewed", { feature, tier }, { userId }),
  checkoutStarted: (targetTier: string, userId: string) =>
    track("aarrr.revenue.checkout_started", { targetTier }, { userId }),
  conversionCompleted: (tier: string, billing: string, userId: string) =>
    track("aarrr.revenue.conversion_completed", { tier, billing }, { userId }),
  upgrade: (fromTier: string, toTier: string, userId: string) =>
    track("aarrr.revenue.upgrade", { fromTier, toTier }, { userId }),
  churned: (tier: string, userId: string, reason?: string) =>
    track("aarrr.revenue.churned", { tier, reason }, { userId }),

  // Referral
  shareCreated: (shareId: string, userId: string) =>
    track("aarrr.referral.share_created", { shareId }, { userId }),
  shareViewed: (shareId: string, referrerCode?: string) =>
    track("aarrr.referral.share_viewed", { shareId, referrerCode }, { uiOnly: true }),
  signupFromShare: (referrerCode: string, userId: string) =>
    track("aarrr.referral.signup_from_share", { referrerCode }, { userId }),
  rewardEarned: (type: string, userId: string) =>
    track("aarrr.referral.reward_earned", { type }, { userId }),
};

// ─── UTM Capture on page load ────────────────────

/**
 * Call once on app mount to capture UTM params.
 * Persists to sessionStorage so they survive redirects.
 */
export function captureUTM(userId?: string): void {
  if (typeof window === "undefined") return;
  const params = new URLSearchParams(window.location.search);
  const utmKeys = ["utm_source", "utm_medium", "utm_campaign", "utm_term", "utm_content", "ref"];
  const captured: Record<string, string> = {};

  for (const key of utmKeys) {
    const val = params.get(key);
    if (val) captured[key] = val;
  }

  if (Object.keys(captured).length > 0) {
    safeSessionStorage.setJSON("funnelforge_utm", captured);
    track("aarrr.acquisition.utm_captured", captured, { userId, uiOnly: true });
  }
}

/** Retrieve previously captured UTM params. */
export function getUTM(): Record<string, string> {
  return safeSessionStorage.getJSON<Record<string, string>>("funnelforge_utm", {});
}

/** Load GA4 SDK and configure it. No-op when VITE_GA4_ID is unset. */
export function initGA4(): void {
  const id = import.meta.env.VITE_GA4_ID as string | undefined;
  if (!id || typeof window === "undefined") return;
  const script = document.createElement("script");
  script.async = true;
  script.src = `https://www.googletagmanager.com/gtag/js?id=${id}`;
  document.head.appendChild(script);
  window.dataLayer = window.dataLayer ?? [];
  window.gtag = function (...args: unknown[]) { window.dataLayer!.push(args); };
  window.gtag("js", new Date());
  window.gtag("config", id, { send_page_view: false });
}
