-- ─────────────────────────────────────────────────────────────────────────────
-- Coach conversation memory — orthogonal per-turn insight tagging
--
-- Design:
--   coach_conversations  groups turns into a logical session (one per browser
--                        tab session; client generates the UUID).
--   coach_messages       stores every user + assistant turn with:
--                          • coach_mode  — HOLD/CLARIFY/STRUCTURE/CHALLENGE/OPERATIONALIZE
--                          • insight_type — orthogonal category of the user's intent:
--                              goal      → user is committing to an action (OPERATIONALIZE)
--                              objection → user is pushing back (CHALLENGE)
--                              context   → user is providing factual context (CLARIFY)
--                              pain      → user is expressing distress (HOLD)
--                            NULL for assistant turns and neutral STRUCTURE turns.
--
-- Orthogonality guarantee:
--   Each insight_type maps to exactly one knowledge_facts predicate when the
--   batch extractor runs (plans_to / resists_objection / experiences_pain).
--   Context turns are ephemeral and NOT written to knowledge_facts to prevent
--   factual leakage from transient conversational framing.
--
-- Evidence chain:
--   evidence_source_table = 'ai_coach_message' is already in the
--   knowledge_facts_evidence_table CHECK constraint.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── coach_conversations ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.coach_conversations (
  id              UUID        PRIMARY KEY,          -- generated by client (crypto.randomUUID)
  user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  plan_id         UUID        REFERENCES public.saved_plans(id) ON DELETE SET NULL,
  turn_count      INTEGER     NOT NULL DEFAULT 0,
  last_coach_mode TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_at       TIMESTAMPTZ
);

ALTER TABLE public.coach_conversations ENABLE ROW LEVEL SECURITY;

CREATE POLICY coach_conversations_rls ON public.coach_conversations
  FOR ALL
  USING     (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ── coach_messages ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.coach_messages (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID        NOT NULL REFERENCES public.coach_conversations(id) ON DELETE CASCADE,
  user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role            TEXT        NOT NULL CHECK (role IN ('user', 'assistant')),
  content         TEXT        NOT NULL CHECK (char_length(content) BETWEEN 1 AND 16000),
  coach_mode      TEXT,
  -- Orthogonal insight classification (user turns only; NULL for assistant turns)
  insight_type    TEXT        CHECK (insight_type IN ('goal', 'objection', 'context', 'pain')),
  tokens_used     INTEGER,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.coach_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY coach_messages_rls ON public.coach_messages
  FOR ALL
  USING     (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Fast path: load last N turns in a conversation
CREATE INDEX IF NOT EXISTS idx_coach_messages_conv_time
  ON public.coach_messages (conversation_id, created_at);

-- Fast path: pull all tagged insights for a user (knowledge graph extraction)
CREATE INDEX IF NOT EXISTS idx_coach_messages_user_insight
  ON public.coach_messages (user_id, insight_type, created_at DESC)
  WHERE insight_type IS NOT NULL;

-- ── Trigger: keep turn_count + last_coach_mode in sync ───────────────────────

CREATE OR REPLACE FUNCTION public.increment_coach_turn()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF NEW.role = 'user' THEN
    UPDATE public.coach_conversations
    SET turn_count      = turn_count + 1,
        last_coach_mode = COALESCE(NEW.coach_mode, last_coach_mode)
    WHERE id = NEW.conversation_id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_coach_turn_count ON public.coach_messages;
CREATE TRIGGER trg_coach_turn_count
  AFTER INSERT ON public.coach_messages
  FOR EACH ROW EXECUTE FUNCTION public.increment_coach_turn();
